/*******************************************************
 Copyright: (c) 2013-2026 Guan Lisheng (guanlisheng@gmail.com)
 Copyright: (c) 2017-2018 Stefano Giorgio (stef145g)
 Copyright: (c) 2022      Mark Whalley (mark@ipx.co.uk)
 Copyright: (c) 2026      George Ef (george.a.ef@gmail.com)

 The code in this file was previously generated by [sqlite2cpp.py]
 ********************************************************/

#include "_TableBase.h"

// Creates the database table if the table does not exist
bool TableBase::ensure_table()
{
    if (!m_db->TableExists(m_table_name)) {
        try {
            m_db->ExecuteUpdate(m_create_query);
            ensure_data();
        }
        catch(const wxSQLite3Exception &e) {
            wxLogError("%s: Exception %s", m_table_name, e.GetMessage().utf8_str());
            return false;
        }
    }

    try {
        for (const auto& query : m_index_query_a)
            m_db->ExecuteUpdate(query);
    }
    catch(const wxSQLite3Exception &e) {
        wxLogError("%s: Exception %s", m_table_name, e.GetMessage().utf8_str());
        return false;
    }

    return true;
}

void TableBase::drop_table()
{
    // TODO: drop indeces on this table
    m_db->ExecuteUpdate(m_drop_query);
}

int64 TableBase::newId()
{
    // Get the current time in milliseconds as wxLongLong/int64
    int64 ticks = wxDateTime::UNow().GetValue();

    // Ensure uniqueness from last generated value
    if (ticks <= m_ticks)
        ticks = m_ticks + 1;
    m_ticks = ticks;

    // Generate a random 3-digit number (0 to 999)
    std::random_device rd;
    std::mt19937 gen(rd());
    std::uniform_int_distribution<int> dist(0, 999);
    int randomSuffix = dist(gen);

    // Combine ticks and randomSuffix
    return (ticks * 1000) + randomSuffix;
}

// Build a select query from the input clauses args and append it into query.
// The placeholder indexes, to be used with wxSQLite3Statement::Bind(),
// are appended into index_a. If index_a is initially empty and i=index_a[p],
// the value of the 0-based p-th placeholder in the constructed query
// shall be bound to the value of the 0-based i-th argument in args.
// Notice that wxSQLite3Statement::Bind() uses 1-based indexes.
// All variadic arguments args are of type TableClauseD or TableClauseV<V>.
void TableBase::select_query(
    wxString& query,
    std::vector<int>& index_a,
    const std::vector<const TableClause*>& clause_na
) {
    // current state of each clause type
    struct State {
        wxString query;
        std::vector<int> index_a;
        bool is_empty = true;
    } state_a[TableClause::CLAUSE_ID_size];

    // stack of logical operators, used in WHERE and PAREN clauses
    std::vector<wxString> op_a;
    op_a.push_back("AND");

    // process clause args
    int clause_i = 0;
    for (const TableClause* clause_n : clause_na) {
        const TableClause& clause = *clause_n;
        State& state = state_a[TableClause::collate_id(clause.m_id)];

        switch (clause.m_id)
        {
        case TableClause::CLAUSE_ID_RESULT:
        case TableClause::CLAUSE_ID_GROUP:
        case TableClause::CLAUSE_ID_ORDER:
            if (!state.is_empty)
                state.query += ", ";
            state.query += clause.m_text;
            state.is_empty = false;
            break;
        case TableClause::CLAUSE_ID_WHERE:
            if (!state.is_empty)
                state.query += " " + op_a.back() + " ";
            state.query += clause.m_text;
            state.is_empty = false;
            break;
        case TableClause::CLAUSE_ID_PAREN:
            if (!clause.m_text.IsEmpty()) {
                if (!state.is_empty)
                    state.query += " " + op_a.back() + " ";
                state.query += "(";
                op_a.push_back(clause.m_text);
                state.is_empty = true;
            }
            else if (op_a.size() > 1) {
                if (state.is_empty)
                    wxLogError("TableBase::select_query: empty condition inside PAREN");
                state.query += ")";
                op_a.pop_back();
                state.is_empty = false;
            }
            else {
                wxLogError("TableBase::select_query: unexpected END");
                // ignore and continue
            }
            break;
        case TableClause::CLAUSE_ID_LIMIT:
            if (!state.is_empty)
                wxLogWarning("TableBase::select_query: multiple LIMIT arguments");
            // keep the last
            state.query = clause.m_text;
            state.is_empty = false;
            break;
        }

        for (int p = 0; p < clause.m_mult; ++p)
            state.index_a.push_back(clause_i);

        clause_i++;
    }

    // close PAREN
    if (op_a.size() > 1) {
        wxLogWarning("TableBase::select_query: missing END");
        int id = TableClause::CLAUSE_ID_WHERE;
        for (std::size_t op_i = 1; op_i < op_a.size(); ++op_i)
            state_a[id].query += ")";
        state_a[id].is_empty = false;
    }

    // update query, index_a
    for (int id = 0; id < TableClause::CLAUSE_ID_size; ++id) {
        if (TableClause::collate_id(static_cast<TableClause::CLAUSE_ID>(id)) != id)
            continue;

        if (id == TableClause::CLAUSE_ID_RESULT) {
            query += state_a[id].is_empty
                ? m_select_query
                : "SELECT " + state_a[id].query + " FROM " + m_table_name;
        }
        else if (!state_a[id].is_empty) {
            switch (id)
            {
            case TableClause::CLAUSE_ID_WHERE:
                query += " WHERE " + state_a[id].query;
                break;
            case TableClause::CLAUSE_ID_GROUP:
                query += " GROUP BY " + state_a[id].query;
                break;
            case TableClause::CLAUSE_ID_ORDER:
                query += " ORDER BY " + state_a[id].query;
                break;
            case TableClause::CLAUSE_ID_LIMIT:
                query += " LIMIT " + state_a[id].query;
                break;
            default:
                break;
            }
        }

        for (int i : state_a[id].index_a)
            index_a.push_back(i);
    }
}
