/*******************************************************
Copyright: (c) 2013-2026 Guan Lisheng (guanlisheng@gmail.com)
Copyright: (c) 2017-2018 Stefano Giorgio (stef145g)
Copyright: (c) 2022      Mark Whalley (mark@ipx.co.uk)
Copyright: (c) 2026      George Ef (george.a.ef@gmail.com)

 The code in this file was previously generated by [sqlite2cpp.py]
 ********************************************************/

#pragma once

#include <vector>
#include <map>
#include <random>
#include <algorithm>
#include <functional>
#include <cwchar>
#include <wx/wxsqlite3.h>
#include <wx/intl.h>
#include <wx/log.h>

#include <rapidjson/document.h>
#include <rapidjson/pointer.h>
#include <rapidjson/prettywriter.h>
#include <rapidjson/stringbuffer.h>
using namespace rapidjson;

#include <html_template.h>
using namespace tmpl;

#include "base/types.h"

class wxString;

enum OP {
    OP_EQ = 0, // EQual
    OP_GT,     // Greater Than
    OP_LT,     // Less Than
    OP_GE,     // Greater or Equal
    OP_LE,     // Less or Equal
    OP_NE      // Not Equal
};

template<typename V>
struct TableOpV
{
    OP m_operator;
    V m_value;

    TableOpV(OP op, const V& v): m_operator(op), m_value(v) {}
};

struct TableBase
{
protected:
    // member variables are independent for each table derived from TableBase
    wxSQLite3Database* m_db;
    int64 m_ticks;
    wxString m_table_name;
    wxString m_create_query;
    wxString m_drop_query;
    wxArrayString m_index_query_a;
    wxString m_insert_query;
    wxString m_update_query;
    wxString m_delete_query;
    wxString m_select_query;

public:
    TableBase(): m_db(0), m_ticks(0) {};
    virtual ~TableBase() {};

    void db_begin() { m_db->Begin(); }
    void db_commit() { m_db->Commit(); }
    void db_savepoint(const wxString name = "MMEX") { m_db->Savepoint(name); }
    void db_release_savepoint(const wxString name = "MMEX") { m_db->ReleaseSavepoint(name); }
    void db_rollback(const wxString name = "MMEX") { m_db->Rollback(name); }

    bool ensure_table();
    void drop_table();
    int64 newId();

    virtual void ensure_data() {};
    virtual void preload_cache(int max_size) = 0;
    virtual void reset_cache() = 0;
    virtual bool cache_empty() const = 0;
    virtual auto stat_json() const -> const wxString = 0;
    virtual void debug_stat() const = 0;
};

