/*******************************************************
 Copyright: (c) 2013-2026 Guan Lisheng (guanlisheng@gmail.com)
 Copyright: (c) 2017-2018 Stefano Giorgio (stef145g)
 Copyright: (c) 2022      Mark Whalley (mark@ipx.co.uk)
 Copyright: (c) 2026      George Ef (george.a.ef@gmail.com)

 The code in this file was previously generated by [sqlite2cpp.py]
 ********************************************************/

#pragma once

#include <vector>
#include <map>
#include <random>
#include <algorithm>
#include <functional>
#include <cwchar>
#include <wx/wxsqlite3.h>
#include <wx/intl.h>
#include <wx/log.h>

#include <rapidjson/document.h>
#include <rapidjson/pointer.h>
#include <rapidjson/prettywriter.h>
#include <rapidjson/stringbuffer.h>
using namespace rapidjson;

#include <html_template.h>
using namespace tmpl;

#include "base/_types.h"
#include "_TableClause.h"

class wxString;

struct TableBase
{
// -- state

protected:
    // member variables are independent for each table derived from TableBase
    wxSQLite3Database* m_db;
    int64 m_ticks;
    wxString m_table_name;
    wxString m_create_query;
    wxString m_drop_query;
    wxArrayString m_index_query_a;
    wxString m_insert_query;
    wxString m_update_query;
    wxString m_delete_query;
    wxString m_select_query;

// -- constructor

public:
    TableBase(): m_db(0), m_ticks(0) {};
    virtual ~TableBase() {};

// -- methods

public:
    void db_begin() { m_db->Begin(); }
    void db_commit() { m_db->Commit(); }
    void db_savepoint(const wxString name = "MMEX") { m_db->Savepoint(name); }
    void db_release_savepoint(const wxString name = "MMEX") { m_db->ReleaseSavepoint(name); }
    void db_rollback(const wxString name = "MMEX") { m_db->Rollback(name); }

public:
    bool ensure_table();
    void drop_table();
    int64 newId();

    template<typename... Args>
    void select_query(wxString& query, std::vector<int>& index_a, const Args&... args);
    void select_query(wxString& query, std::vector<int>& index_a,
        const std::vector<const TableClause*>& clause_na
    );

    template<typename Arg1>
    void bind_stmt(
        wxSQLite3Statement& stmt,
        const std::vector<int>& index_a,
        int index,
        const Arg1& arg1
    );

    template<typename Arg1, typename... Args>
    void bind_stmt(
        wxSQLite3Statement& stmt,
        const std::vector<int>& index_a,
        int index,
        const Arg1& arg1, const Args&... args
    );

// -- virtual

public:
    virtual void ensure_data() {};
    virtual void preload_cache(int max_size) = 0;
    virtual void reset_cache() = 0;
    virtual bool cache_empty() const = 0;
    virtual auto stat_json() const -> const wxString = 0;
    virtual void debug_stat() const = 0;
};

// -- template

template<typename... Args>
void TableBase::select_query(wxString& query, std::vector<int>& index_a, const Args&... args)
{
    static_assert(
        (std::is_base_of<TableClause, Args>::value && ...),
        "Args must derive from TableClause"
    );
    select_query(query, index_a, {&args...});
}

// The input argument arg1 is of type TableClauseD or TableClauseV<V>.
// Bind the placeholders { p+1 | index_a[p] == index } to the value in arg1.
// Notice that p is 0-based, while wxSQLite3Statement::Bind() uses 1-based indexes.
// If arg1 is of type TableClauseD, then the above set of placeholders must be empty.
template<typename Arg1>
void TableBase::bind_stmt(
    wxSQLite3Statement& stmt,
    const std::vector<int>& index_a,
    int index,
    const Arg1& arg1
) {
    static_assert(
        std::is_base_of<TableClause, Arg1>::value,
        "Arg1 must derive from TableClause"
    );

    for (int p = 0; p < index_a.size(); ++p) {
        if (index_a[p] == index)
            stmt.Bind(p+1, arg1.m_value);
    }
}

// This method is recursive over args.
// The input arguments arg1, args are of type TableClauseD or TableClauseV<V>,
// where the value type V may be different for different arguments.
template<typename Arg1, typename... Args>
void TableBase::bind_stmt(
    wxSQLite3Statement& stmt,
    const std::vector<int>& index_a,
    int index,
    const Arg1& arg1, const Args&... args
) {
    bind_stmt(stmt, index_a, index, arg1);
    bind_stmt(stmt, index_a, index+1, args...);
}
