/*******************************************************
Copyright: (c) 2013-2026 Guan Lisheng (guanlisheng@gmail.com)
Copyright: (c) 2017-2018 Stefano Giorgio (stef145g)
Copyright: (c) 2022      Mark Whalley (mark@ipx.co.uk)
Copyright: (c) 2026      George Ef (george.a.ef@gmail.com)

 The code in this file was previously generated by [sqlite2cpp.py]
 ********************************************************/

#include "_TableBase.h"

// Creates the database table if the table does not exist
bool TableBase::ensure_table()
{
    if (!m_db->TableExists(m_table_name)) {
        try {
            m_db->ExecuteUpdate(m_create_query);
            ensure_data();
        }
        catch(const wxSQLite3Exception &e) {
            wxLogError("%s: Exception %s", m_table_name, e.GetMessage().utf8_str());
            return false;
        }
    }

    try {
        for (const auto& query : m_index_query_a)
            m_db->ExecuteUpdate(query);
    }
    catch(const wxSQLite3Exception &e) {
        wxLogError("%s: Exception %s", m_table_name, e.GetMessage().utf8_str());
        return false;
    }

    return true;
}

void TableBase::drop_table()
{
    // TODO: drop indeces on this table
    m_db->ExecuteUpdate(m_drop_query);
}

int64 TableBase::newId()
{
    // Get the current time in milliseconds as wxLongLong/int64
    int64 ticks = wxDateTime::UNow().GetValue();

    // Ensure uniqueness from last generated value
    if (ticks <= m_ticks)
        ticks = m_ticks + 1;
    m_ticks = ticks;

    // Generate a random 3-digit number (0 to 999)
    std::random_device rd;
    std::mt19937 gen(rd());
    std::uniform_int_distribution<int> dist(0, 999);
    int randomSuffix = dist(gen);

    // Combine ticks and randomSuffix
    return (ticks * 1000) + randomSuffix;
}

